# Generated by Django 5.1.7 on 2025-03-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadimage_alter_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='size',
            new_name='filesize',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='is_color',
            new_name='is_grayscale',
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
