# Generated by Django 5.1.7 on 2025-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_rename_size_file_filesize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=1024),
        ),
    ]
