# Generated by Django 5.1.7 on 2025-03-13 07:29

import files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=files.storage.PreserveOriginalNameStorage(), upload_to='uploads/'),
        ),
    ]
