# Generated by Django 5.1.7 on 2025-03-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_delete_uploadimage_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
